version: '3.8'

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./tls.crt:/etc/caddy/tls.crt
      - ./tls.key:/etc/caddy/tls.key
      - ./data/config:/config
      - ./data/data:/data

